# Generated by Django 4.1 on 2022-08-18 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sending_attempts', models.PositiveIntegerField(default=0)),
                ('sended', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('return_from_receiver_text', models.TextField(blank=True, null=True)),
                ('return_from_receiver_json', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('method', models.CharField(default='post', max_length=255)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('authentication', models.CharField(choices=[('0', 'No authentication'), ('1', 'Basic authentication'), ('2', 'JWT authentication'), ('3', 'API Key authentication')], default='0', max_length=1)),
                ('auth_username', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_password', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('url_token', models.URLField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='webhook.webhook')),
            ],
        ),
    ]
